### ISSUE TITLE
Add support for multitenant context brokers (FIWARE-Service header)

### ISSUE THREAD

**Issue by aarranz** [wirecloud-fiware/ngsi-browser-widget#1]
This request comes from [StackOverflow](http://stackoverflow.com/questions/33452246/fiware-wirecloud-fiware-service-http-header-needed-for-orion-cb)

Basically, we need to add a new preference for indicating what tenant we want to use for connecting to the context broker (if the preference is empty, then the FIWARE-Service header is not used)

**Comment by justb4** [comment]
Ok, thanks, was thinking of a PR with a similar fix in these files but you made the changes already. NGSI Browser v1.0.1 from Marketplace works with tenant feature!
